### ISSUE TITLE
Use automated script to convert to LaTeX document

### ISSUE THREAD

**Issue by mattpitkin** [mattpitkin/living_rev_article#1]
I should probably switch to using a script such as @eteq's [authorea_build](https://github.com/eteq/authorea-scripts) script to convert the authorea structure into LaTeX. This would make things more future proof. I would have to use an editted version of the script though, due to necessities of the epubtk style file (unless Springer change the style file needed!)

**Comment by eteq** [comment]
@mattpitkin - I'm happy for you to use the script and modify it as you suggest, but can you do a pull request to [eteq/authorea-scripts](https://github.com/eteq/authorea-scripts) with the epubtk alterations?  That way others can make use of it in the future and they don't have to go tracking down a bunch of different repos.

I'm happy to discuss in more detail how you might do this, but perhaps that fits better in the [eteq/authorea-scripts](https://github.com/eteq/authorea-scripts) issue tracker?

**Comment by mattpitkin** [comment]
@eteq - Sure, I'll make an Issue request there and fork the repo to see if I can make the required changes. The main things this would involve is putting \epubtk commands around figures and authors if required.

**Comment by mattpitkin** [comment]
I think I'll be able to use the build script without having to edit it. I've found that most of the things that I'd want to include can actually be done (provided that you're using LaTeXML as the authorea backend) using `\iflatexml ... \else ... \fi` commands in preamble.tex to put in epubtk specific things.

Ultimately the solution would be be try and include the epubtk style file in the allowed [latexml packages](https://github.com/brucemiller/LaTeXML/tree/master/lib/LaTeXML/Package), but this is not something I think I'll do soon.
